### ISSUE TITLE
DF Curvy Walls: Won't draw

### ISSUE THREAD

**Issue by miromonti** [flamewave000/dragonflagon-fvtt#292] opened 2022-01-08 23:13 UTC
**Module**
DF Curvy Walls v3.2.4
Foundry VTT v9 build242

**Describe the issue**
It just won't draw.

**To Reproduce**
1. Go to Wall Controls.
2. Choose any wall or door.
3. Choose any CW option.
4. Nothing draws.

I used Find the culprit and isolated DF Curvy Walls, lib-wrapper, and lib-df-hotkeys. With just those active (and Find the culprit), DF Curvy Walls simply won't draw.

**Expected behavior**
Walls. Drawn.

**Screenshots (Optional)**
Here are screenshots of some errors, as well as a log of them:
![Screen Shot 2022-01-08 at 3 04 32 PM](https://user-images.githubusercontent.com/38819125/148663014-2ed1a819-07a9-47ab-9027-2e5c3dbbc3c7.png)
[DFCurvyWalls-1641682799349.log](https://github.com/flamewave000/dragonflagon-fvtt/files/7834165/DFCurvyWalls-1641682799349.log)

**Comment by flamewave000** [comment] 2022-01-09 01:55
Duplicate of #260

**Closed by flamewave000** 2022-01-09 01:55 UTC
Labels: bug
