### ISSUE TITLE
DF Chat Enhancements - Public Roll button is missing + Can't hide Chat Archive button

### ISSUE THREAD

**Issue by zLaddeus** [flamewave000/dragonflagon-fvtt#284] opened 2022-01-05 13:30 UTC
**Module**
DF Chat Enhancements v.3.5.1

**Describe the issue**
When using "Roll Buttons: Replace roll type selector with buttons" the Public roll button isn't available, as the GM.

![image](https://user-images.githubusercontent.com/71599968/148225313-bab7de77-7e96-4f71-b10c-d2442ce2c685.png)

Same goes with "Chat Archive: Hide the Export Chat log button" it's still there.

Cheers

**Comment by flamewave000** [comment] 2022-01-05 15:35
Duplicate of #269. Please wait for the public release of DF Chat Enhancements for FoundryVTT V9.

**Closed by flamewave000** 2022-01-05 15:35 UTC
Labels: bug
