### ISSUE TITLE
DF Chat Enhancement preventing to sending messages with enter

### ISSUE THREAD

**Issue by fabiocmg** [flamewave000/dragonflagon-fvtt#294] opened 2022-01-09 04:14 UTC
Hello. I'm using Foundry v9 (B242) and recently the DF Chat Engancement module created a bug. The enter button is no sending from the chat box anymore. Instead, it is only breaking lines, like it does with shift+enter. 

Rolls and messages sent directly from the character sheet goes to the chat normally. The bug is in the chat box.

**Comment by flamewave000** [comment] 2022-01-09 05:46
Duplicate of #243

**Comment by flamewave000** [comment] 2022-01-09 05:47
DF Chat Enhancements has just received an update for support of V9 tonight. Please install that new version.

**Closed by flamewave000** 2022-01-09 05:47 UTC
Labels: bug
