### ISSUE TITLE
DF Chat Enhancements: Public Roll button now missing

### ISSUE THREAD

**Issue by amcvfx** [flamewave000/dragonflagon-fvtt#286] opened 2022-01-06 16:03 UTC
**Module**
DF Chat Enhancements v3.5.1

**Describe the issue**
The Public rolling button above the chat window seems to be missing, with only the other 3 options now visible.

![image](https://user-images.githubusercontent.com/35099081/148412277-aa809d33-909a-4920-9bde-4cb4777b1359.png)

**Comment by flamewave000** [comment] 2022-01-06 16:41
Duplicate of #269. Please wait for the public release of DF Chat Enhancements for FoundryVTT V9.

**Closed by flamewave000** 2022-01-06 16:41 UTC
Labels: bug
