### ISSUE TITLE
DF Curvy Walls: Button Overflow Module Conflict

### ISSUE THREAD

**Issue by Cubius** [flamewave000/dragonflagon-fvtt#319] opened 2022-03-05 16:34 UTC
** Conflicting Module(s)**
- [Button Overflow](https://foundryvtt.com/packages/buttonoverflow)

**Describe the conflict**
The buttons to toggle drawing curved walls become unresponsive. They're still rendered - in case of a button overflow they will be rendered underneath the overflowing buttons - but do not react to being clicked.

**Screenshots (Optional)**
Overlap Problem:
![image](https://user-images.githubusercontent.com/15717384/156892034-de5a6a8d-ec81-41d4-8f7b-621cb62388e0.png)
(Even with a taller screen where the buttons do not overlap, the issue of the buttons being unresponsive persists.)

**Additional context (Optional)**
The modules did not conflict in Foundry v8. I'm not certain as of which v9 build they are incompatible.

**Comment by flamewave000** [comment] 2022-03-06 01:14
Duplicate of #296

**Closed by flamewave000** 2022-03-06 01:14 UTC
