### ISSUE TITLE
DF setting clarity messes with module management+

### ISSUE THREAD

**Issue by Orionox** [flamewave000/dragonflagon-fvtt#348] opened 2022-03-26 15:16 UTC
**Module**
The search function of DF settings clarity does not work properly with module managment+. If you search anything in the fuzzy search of DF settingy clarity it breaks the module setting page and combines the dialog for each module into a jumbled mess. 
**To Reproduce**

1.  Activate DF setting clarity and Module managemnt  +
2. Open module setting
3. search for anything in the DF setting clarity fuzzy search. 
4. If the foundry doesn't freeze (Anothe bug is that sometimes when I search something and there are 0 results foundry will freeze and require restart)
5. Look at any of the settings for a module
6. All of the dialogs in each module setting will be scrambled and messy.
7. Closing and re-opening moduel settings fixes the problem so long as you don't touch the fuzzy search box. 

**Screenshots
![Capture](https://user-images.githubusercontent.com/20059838/160245857-cbf2bb28-b9fa-46a3-9d5b-6031a1b530bf.PNG)
![Capture](https://user-images.githubusercontent.com/20059838/160245871-4a30cc4d-824b-4252-ab62-50991ac89ab8.PNG)

 (Optional)**

**Comment by flamewave000** [comment] 2022-03-27 20:33
Duplicate of #345

**Closed by flamewave000** 2022-03-27 20:33 UTC
Labels: bug
