### ISSUE TITLE
DF Scene Enhancement: Conflicts with Cards Tab

### ISSUE THREAD

**Issue by CptTwinkie** [flamewave000/dragonflagon-fvtt#289] opened 2022-01-08 11:48 UTC
**Module**
DF Scene Enhancement v3.4.2

**Describe the issue**
The sidebar panels (right side) are offset to the left (by the width of the sidebar, it's not a small amount).
The cards tab is missing.
Inspecting the extra spacing in devtools I find the invisible cards content.

**To Reproduce**
1. Foundry v9 Build 240
2. Starfinder 0.17.0
3. DF Scene Enhancement
4. Sidebar is offset when loaded (by a large amount)
Bonus: Turn off DF Scene Enhancement and the problem goes away (confirmation of cause)

**Expected behavior**
The sidebar loads at the right edge of the screen

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/2079751/148642879-dee239f8-c69d-4093-b8b9-0613c352a339.png)

**Console**
foundry.js:316 A: Error detected in module DF Scene Enhancement. It is likely this module has not been updated for FVTT Version 9.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-scene-enhance
Report this issue here: https://github.com/flamewave000/dragonflagon-fvtt/issues

== Technical Details:
Detected by libWrapper.
Package ID= df-scene-enhance
Error= libWrapper: Can't wrap 'SceneDirectory.prototype._onClickEntityName', target does not exist or could not be found.

[Detected 1 package: df-scene-enhance]
    at new 🎁constructor (https://dawn-of-flame.deepflame.nl/modules/lib-wrapper/lib-wrapper.js:1:25841)
    at https://dawn-of-flame.deepflame.nl/modules/lib-wrapper/lib-wrapper.js:1:43138
    at ce (https://dawn-of-flame.deepflame.nl/modules/lib-wrapper/lib-wrapper.js:1:43171)
    at Function.🎁register [as register] (https://dawn-of-flame.deepflame.nl/modules/lib-wrapper/lib-wrapper.js:1:46272)
    at Function.patchSceneDirectoryClick (https://dawn-of-flame.deepflame.nl/modules/df-scene-enhance/src/df-scene-enhance.js:5:840)
    at Function.ready (https://dawn-of-flame.deepflame.nl/modules/df-scene-enhance/src/df-scene-enhance.js:5:4521)
    at https://dawn-of-flame.deepflame.nl/modules/df-scene-enhance/src/df-scene-enhance.js:11:447
    at Function._call (https://dawn-of-flame.deepflame.nl/scripts/foundry.js:294:14)
    at Function.callAll (https://dawn-of-flame.deepflame.nl/scripts/foundry.js:253:12)
    at Game.setupGame (https://dawn-of-flame.deepflame.nl/scripts/foundry.js:5547:11)
    at async Game._initializeGameView (https://dawn-of-flame.deepflame.nl/scripts/foundry.js:6479:5)
    at async Game.initialize (https://dawn-of-flame.deepflame.nl/scripts/foundry.js:5415:5)
onError	@	foundry.js:316
🎁call_wrapped	@	libWrapper-wrapper.js:510
🎁Hooks.onError#lib-wrapper	@	listeners.js:137
🎁Hooks.onError#0	@	libWrapper-wrapper.js:186
_call	@	foundry.js:298
callAll	@	foundry.js:253
setupGame	@	foundry.js:5547

**Comment by flamewave000** [comment] 2022-01-08 14:48
Duplicate of #264 and #242. The public release of DF Scene Enhancements should be sometime today.

**Closed by flamewave000** 2022-01-08 14:48 UTC
Labels: bug
