### ISSUE TITLE
DF Curvy walls: Not working in V9

### ISSUE THREAD

**Issue by yogiteck** [flamewave000/dragonflagon-fvtt#287] opened 2022-01-07 09:44 UTC
**Module**
DF Curvy Walls v3.2.4

**Describe the issue**
Not working when I try to draw any form (square, circle, ...). Got this javascript error :
Uncaught TypeError: Cannot read properties of undefined (reading 'removeChildren')
[Detected 2 packages: df-curvy-walls, lib-wrapper]
    at CurvyWallToolManager.render (CurvyWallToolManager.ts:237) 

**To Reproduce**
1. Install DD5e or PF2
2. Activate only DF Curvy walls with its dependencies
3. Create a map
4. Try to draw
5. No preview appears on the screen

**Expected behavior**
The preview should appear

**Comment by flamewave000** [comment] 2022-01-07 15:37
Duplicate of #260. DF Curvy Walls is currently in Patron-only pre-release testing. Please wait for the V9 compatible version to be released publicly.

**Closed by flamewave000** 2022-01-07 15:37 UTC
Labels: bug
