### ISSUE TITLE
DF Chat Enhance: Error when rendering chat buttons: "Unknown roll type 'publicroll'"

### ISSUE THREAD

**Issue by Varriount** [flamewave000/dragonflagon-fvtt#275] opened 2022-01-02 23:31 UTC
**Module**
DF Chat Enhance v3.5.1

**Describe the issue**
When Foundry loads, the following error appears in the browser console:
```
Error: Unknown roll type 'publicroll'
    handleChatLogRendering <snip>/modules/df-chat-enhance/src/main.js:1
    _call <snip>/scripts/foundry.js:294
    call <snip>/scripts/foundry.js:279
    _render <snip>/scripts/foundry.js:3086
    _render <snip>/scripts/foundry.js:46675
    _render <snip>/scripts/foundry.js:57264
    _render <snip>/scripts/foundry.js:46463
    render <snip>/scripts/foundry.js:2990
    initializeUI <snip>/scripts/foundry.js:5587
    setupGame <snip>/scripts/foundry.js:5480
    _initializeGameView <snip>/scripts/foundry.js:6434
    _initializeView <snip>/scripts/foundry.js:6410
    initialize <snip>/scripts/foundry.js:5380
    call_wrapped <snip>/modules/lib-wrapper/lib-wrapper.js:1
    libWrapperInit <snip>/modules/lib-wrapper/lib-wrapper.js:1
    initialize#0 <snip>/modules/lib-wrapper/lib-wrapper.js:1
    <anonymous> <snip>/scripts/foundry.js:62192
    async* <snip>/scripts/foundry.js:62174
    main.js:1:42096
```

**To Reproduce**
1. Load Foundry with "DF Chat Enhance" enabled, and with "Roll Buttons" enabled.

**Expected behavior**
No error should occur.

**Comment by flamewave000** [comment] 2022-01-02 23:37
Duplicate of #269

This issue is V9 specific. Please wait for V9 compatibility to be released.

**Closed by flamewave000** 2022-01-02 23:37 UTC
Labels: bug
