### ISSUE TITLE
DF Chat Enhancements: Unable to send message.

### ISSUE THREAD

**Issue by victordiehl** [flamewave000/dragonflagon-fvtt#290] opened 2022-01-08 19:51 UTC
**Module**
DF Chat Enhancements v3.5.1

**Describe the issue**
unable to send message

**To Reproduce**
1. Hit enter after texting.

**Expected behavior**
When typing it generates an error as shown in the image, then does not allow sending the message

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/14099496/148657818-a6b697ae-e406-47e1-bb3a-366a2d123647.png)

**Comment by flamewave000** [comment] 2022-01-08 22:06
Duplicate of #261

**Closed by flamewave000** 2022-01-08 22:06 UTC
Labels: bug
