### ISSUE TITLE
DF Chat Enhancement: I can't send chat messages

### ISSUE THREAD

**Issue by smoothingplane** [flamewave000/dragonflagon-fvtt#280] opened 2022-01-04 15:49 UTC
**Module**
DF Chat Enhancement 3.5.1

**Describe the issue**
When I try to send any type of message from the box at the bottom right, as soon as I hit enter, it just goes to the new paragraph, without sending. (I tried with all modules disabled except for chatcommands and libwrapper and in another pc, the problem persists)

**To Reproduce**
1. Go to Chat Box
2. Type something
3. Press Enter
4. See error (not sending)

**Expected behavior**
Sending the message

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/43862671/148085704-43eff44f-b125-4f92-a8d1-77f5f2806c2f.png)

**Comment by flamewave000** [comment] 2022-01-04 16:07
Duplicate of #261. Please wait for the public release of DF Chat Enhancements for FoundryVTT V9.

**Closed by flamewave000** 2022-01-04 16:07 UTC
Labels: bug
