### ISSUE TITLE
DF Chat Enhancement: Editable Roll/Item Cards/Div

### ISSUE THREAD

**Issue by shinkei13** [flamewave000/dragonflagon-fvtt#60] opened 2021-02-22 03:05 UTC
**Module**
DF Chat Enhancement 2.0.0

**Describe the issue**
Pencils are available to edit text boxes for chat-cards, items, spells, and other module messages that start with `<div>`. Since many modules, including most rolling enhancements. If you edit that html, then it will break the chat card completely.

**To Reproduce**
1. Use any item or spell.
2. Click on the pencil to edit.
3. The chat editor would list the html for said chat card. Example: <div class="dnd5e chat-card item-card" data-actor-id="T73Iaa1lCobw9nws" data-item-id="8GxhhNCZCiEfiqGS">
4. See error.

**Expected behavior**
The module should exclude any chat boxes where <div class="message-content"> contains any html, any <div> tags, or anything but text.

**Screenshots (Optional)**
<img width="400" alt="Screen Shot 2021-02-21 at 9 04 37 PM" src="https://user-images.githubusercontent.com/33383758/108651920-698aa400-7488-11eb-8448-84afedcd7721.png">

**Comment by flamewave000** [comment] 2021-02-22 04:32
This is more of an enhancement request. Having those cards editable doesn't break anything, and is working as intended. It can only possibly break if a user explicitly edits the card and saves the changes (closing the dialog will not save the changes). If this is opened accidentally, it may be beneficial for me to add a Cancel button to make a clearer "way out".

Also, users can enter HTML into the chat box to format their messages and it is supported/accepted by FoundryVTT Core. This may make it impossible to determine which messages should not be editable.

**Comment by shinkei13** [comment] 2021-02-22 14:56
That's fair. Is it possible to make an "exclusions list" for certain messages that should not be editable? If that was the case, something as simple as "<div" would exclude any problematic item cards. Even if it only searches the first word or two of a chat message?

**Comment by flamewave000** [comment] 2021-02-22 15:55
Yeah, I could look at adding a Chat Edit Filter list menu to the module's settings. Different game systems will likely have different HTML in their auto-chat posts. With the filter list, I can leave it up to the GM to decide what to filter out, but also could add some default filters.

**Comment by flamewave000** [comment] 2021-03-12 01:35
I've added a cancel button for now. I'll have to look at adding the filter list in a future release as it will require a fair amount of effort.

**Closed** 2021-06-29 21:17 UTC
Labels: enhancement
