### ISSUE TITLE
DF template Enhancements: Not working with V11

### ISSUE THREAD

**Issue by TheXeno30** [flamewave000/dragonflagon-fvtt#490] opened 2023-08-26 10:08 UTC
**Module**
DF template Enhancements

**Describe the issue**
Doesn't work with V11 

**To Reproduce**
N/A

**Expected behavior**

**Screenshots (Optional)**
If applicable, add screenshots to help explain your problem. If you hit the [F12] key while in Foundry, you will see a window appear. Open the "Console" tab (if it's not already open). If you scroll through this, it is a log for the page. Anything that appears in RED are errors. You can screenshot those errors and add them to this ticket.

**Comment by DiceAndEasy** [comment] 2023-09-12 10:46
I experienced this too as I just switched to v11. When I launch my Foundry world, I get the below error message and when I used Fireball and placed down the template, the entire world crashed and I had to refresh.

![image](https://github.com/flamewave000/dragonflagon-fvtt/assets/86520580/07d56888-3853-4119-98c5-0fdaa6e20547)

**Comment by Shayulghul** [comment] 2023-09-14 08:17
I have the same issue in the desktop app.

**Comment by TheXeno30** [comment] 2023-11-08 12:10
any news on this one? :)

**Comment by mfozz** [comment] 2023-11-08 12:27
Sadly, I think these modules have been abandoned. the DF GitHub and Patreon haven't been updated in about a year.

**Comment by atrak** [comment] 2023-11-14 05:39
Here are some details on the error, just in case someone ends up looking into it.

== Technical Details:
Detected by libWrapper.
Package ID= df-scene-enhance
Error= Can't wrap 'SceneDirectory.prototype._onClickDocumentName', target does not exist or could not be found.

[Detected 2 packages: lib-wrapper, df-scene-enhance]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at DFSceneNav.patchSceneDirectoryClick (df-scene-nav.ts:21:15)
    at DFSceneNav.ready (df-scene-nav.ts:124:14)
    at Object.fn (df-scene-enhance.ts:20:2)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8721:11)
    at async Game._initializeGameView (foundry.js:9962:5)
    at async Game.initialize (foundry.js:8625:5)

**Comment by Dehrangerz9** [comment] 2023-11-17 04:49
i loved this module...

**Comment by david-simoes-93** [comment] 2024-01-11 20:43
Duplicate of https://github.com/flamewave000/dragonflagon-fvtt/issues/481
Comment there shows how to fix it

**Closed** 2024-11-13 21:43 UTC
Labels: bug
