### ISSUE TITLE
DF Chat Enhancement: user.getFlag() doesn't exist

### ISSUE THREAD

**Issue by Eligarf** [flamewave000/dragonflagon-fvtt#232] opened 2021-12-09 02:18 UTC
**Module**
DF Chat Enhancements v3.5.1

**Describe the issue**
Error spew pops out all the time when running in foundry 8.9
`PlayerColor.ts:42 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getFlag')
[Detected 1 package: df-chat-enhance]
    at ChatMessage.🎁ChatMessage.prototype.getHTML#df-chat-enhance (PlayerColor.ts:42)
    at async ChatLog._ChatLog_postOne (scroll-manage.ts:87)
🎁ChatMessage.prototype.getHTML#df-chat-enhance @ PlayerColor.ts:42
await in 🎁ChatMessage.prototype.getHTML#df-chat-enhance (async)
🎁call_wrapper @ libWrapper-wrapper.js:584
🎁ChatLog.prototype.postOne#0 @ libWrapper-wrapper.js:184
_onCreate @ foundry.js:13125
callback @ foundry.js:8765
(anonymous) @ foundry.js:8716
_handleCreateDocuments @ foundry.js:8716
_createDocuments @ foundry.js:8612
await in _createDocuments (async)
create @ backend.mjs:96
await in create (async)
createDocuments @ document.mjs:332
create @ document.mjs:431
(anonymous) @ combat-turn.js:22
_call @ VM16870:4
callAll @ foundry.js:153
callback @ foundry.js:9158
(anonymous) @ foundry.js:9098
_handleDeleteDocuments @ foundry.js:9098
_deleteDocuments @ foundry.js:9008
await in _deleteDocuments (async)
delete @ backend.mjs:215
await in delete (async)
deleteDocuments @ document.mjs:402
delete @ document.mjs:463
callback @ foundry.js:20729
submit @ foundry.js:20673
_onClickButton @ foundry.js:20636
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
PlayerColor.ts:42 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getFlag')
[Detected 1 package: df-chat-enhance]
    at ChatMessage.🎁ChatMessage.prototype.getHTML#df-chat-enhance (PlayerColor.ts:42)
    at async ChatLog._ChatLog_postOne (scroll-manage.ts:87)
    at async ChatLog.updateMessage (foundry.js:32766)
`

**To Reproduce**
Just run with midiqol/dae/etc.

**Expected behavior**
A quick check of game.users shows that this getFlags function doesn't exist within the users in that array

**Screenshots (Optional)**
If applicable, add screenshots to help explain your problem. If you hit the [F12] key while in Foundry, you will see a window appear. Open the "Console" tab (if it's not already open). If you scroll through this, it is a log for the page. Anything that appears in RED are errors. You can screenshot those errors and add them to this ticket.

**Comment by flamewave000** [comment] 2022-04-03 16:43
Might relate to #231

**Comment by flamewave000** [comment] 2022-05-30 15:23
Duplicate of #231

**Closed by flamewave000** 2022-05-30 15:23 UTC
Labels: bug, investigation
