### ISSUE TITLE
DF Module Name: Summarize issue...

### ISSUE THREAD

**Issue by Erfar** [flamewave000/dragonflagon-fvtt#293] opened 2022-01-09 00:20 UTC
**Module**
DF Chat Enhancements 3.5.1

**Describe the issue**
can't send any messages in chat

**To Reproduce**
1. Run fresh new world with only DF Chat Enhancements 3.5.1 and DF Curvy Walls 3.2.4 (and modules that required for them)
2. Try to write anything

libWrapper-wrapper.js:672 Uncaught TypeError: game.keyboard.getKey is not a function
[Detected 3 packages: df-chat-enhance, lib-wrapper, _chatcommands]
    at ChatLogPF2e.🎁ChatLog.prototype._onChatKeyDown#df-chat-enhance (df-chat-edit.ts:45)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:619)
    at ChatLogPF2e.🎁ChatLog.prototype._onChatKeyDown#0 (libWrapper-wrapper.js:188)
    at HTMLTextAreaElement.jumpToMenuHandler (Autocomplete.mjs:219)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2)
    at HTMLTextAreaElement.v.handle (jquery.min.js:2)

[2022-01-09 02-14-21.zip](https://github.com/flamewave000/dragonflagon-fvtt/files/7834248/2022-01-09.02-14-21.zip)

I recorded bug process with opened console on video (mkv file in zip)

**Comment by flamewave000** [comment] 2022-01-09 01:55
Duplicate of #261

**Closed by flamewave000** 2022-01-09 01:55 UTC
Labels: bug
