### ISSUE TITLE
DF Manual Rolls: Input being requested twice

### ISSUE THREAD

**Issue by Evilcalamari** [flamewave000/dragonflagon-fvtt#76] opened 2021-03-15 16:21 UTC
**Module**
DF Manual Rolls v1.2.1

**Describe the issue**
When executing damage or attack rolls in foundry DND 5e, the dialogue box for each roll appears twice. For example, casting Fire Bolt as a first level player - the correct input should be one dialogue box for the ranged spell attack (1d20) and one dialogue box for damage (1d10).

Currently, the dialogue box appears twice for each roll - ie two dialogue boxes requesting a d20 attack input appear back-to-back and two dialogue boxes requesting a d10 damage input appear back-to-back. If multiple rolls are required the dialogue boxes are doubled. So, for example, if a 5th level player casts firebolt, there will be 2 d20 attack inputs and 4 d10 damage inputs (when there should only be 1d20 input and 2d10 input respectively).

Interestingly, only the first input is actually output into the chat box. 

**To Reproduce**

1. Activate any attack or spell (abilities requiring saving throws also experience this bug)
2. Input appropriate values into dialogue boxes
3. Duplicate boxes appear

Note this behavior occurs when I am logged in as the GM - I have not been able to test it with a player yet.

Active mods: 
adventuremusic--v1.1.0;
ambientdoors--v2.2.3;
autocomplete-whisper--v0.3.3;
BetterAmbientLoop--v1.1.2.1;
CommunityLighting--v0.3.1;
forge-vtt-shared-compendiums-critical-hits--vv1.0;
ddb-importer--v0.6.7;
deselection--v1.4.4;
df-manual-rolls--v1.2.1;
dice-so-nice--v3.3.2;
dice-tooltip--v1.0.8;
dice-calculator--v0.6.6;
dae--v0.2.56;
forien-quest-log--v0.5.3;
foundry_community_macros--v0.35;
fxmaster--v1.0.3;
gm-notes--v0.3;
gm-screen--v2.3.1;
hey-wait--v0.3.0;
vtta-iconizer--v2.1.15;
animated-spell-effects--v0.6.8;
laptop-fix--v0.0.8;
lmrtfy--v1.12;
lib-wrapper--v1.3.5.0;
lootsheetnpc5e--v2.5.2;
magicitems--v2.0.8;
mess--v0.13.0;
michaelghelfi--v1.2;
midi-qol--v0.3.88;
multilevel-tokens--v1.3.4;
parallaxia--v0.2.13;
permission_viewer--v0.8.5;
pings--v1.2.10;
playlist-ui--v1.0.0;
polyglot--v1.5.6.7;
forge-vtt-shared-compendiums-revised-critical-hits--vv1.0;
scene-transitions--v0.0.7;
select-tool-everywhere--v1.1.1;
SoundBoard--v1.1.10;
tabletop-rpg-music--v1.2.1;
furnace--v2.6.0;
tidy5e-sheet--v0.4.24;
tidy-ui_game-settings--v0.1.21;
token-action-hud--v1.0.5;
token-attacher--v4.0.1;
token-auras--v1.8;
vtta-tokenizer--v2.2.7;
trigger-happy--v0.8.1;

**Expected behavior**
Only one dialogue box per roll should appear.

**Comment by plutoneld** [comment] 2021-03-16 11:08
I'm unable to reproduce this in my world.

You should probably test this in a new world without the active modules, or use Find the Culprit to see which module is interfering.

**Comment by flamewave000** [comment] 2021-03-16 14:32
This is indeed most likely another module that is doubling rolls. If it is requesting multiple rolls and then throwing away the second, there may not be anything I can do to prevent that. Sometimes modules will request a second roll to get the Max or Min value, but those are already ignored and just given the value immediately without prompting the user.

**Comment by Evilcalamari** [comment] 2021-03-16 15:13
On testing, the issue seems to be from an interaction with Midi-QOL. I am trying to find the exact setting that causes it.

**Comment by Evilcalamari** [comment] 2021-03-16 15:44
Ok, on testing, it seems that Midi-Qol is the conflict.

Two settings in particular replicate the results "Add damage buttons to chat message" and "Enable roll automation support"

Interestingly, both have to be disabled to eliminate duplicate dialogues. Furthermore, "enable roll automation support" causes the duplicate dialogues even if all settings are disabled in "workflow settings"

**Comment by dinerBox** [comment] 2021-03-25 11:35
Hi flamewave,

Just wanted to confirm what evilcalamari said. I get the same conflict with midi qol (on damage rolls only). I believe it is also present when better rolls for 5e is active. Also thank you for the amazing work you do for the community, it is sincerely appreciated.

**Comment by yodasthicc** [comment] 2021-04-02 01:08
I can confirm, I have this same exact issue. I disabled every module but Manual Rolls and Midi and when those two options are checked in Midi I get multiple prompts for damage only. The weird thing is that it happens no matter the player. If any player makes a damage roll - that player gets multiple prompts (seems like 2-3 dice prompts depending on what's checked in Midi) and every other player and the GM gets 1 prompt for a damage roll as well. Turning off those two options in Midi does fix the problem, but then the automated damage system is turned off which is really unfortunate. It doesn't happen on the attack rolls. It almost seems like Midi is requesting the damage result to apply it to the tokens and Manual Rolls is doing two things - responding to the initial roll for the damage and then responding to the Midi asking for the auto implementation of damage. I'm not sure what the 3rd roll set is for when it happens. I'm not a programmer in the least, but that's just what it seems. I'd also be more than happy to assist in fixing this as I can easily reproduce the issue. Let me know and I can be available on Discord to share my screen.

**Comment by flamewave000** [comment] 2021-05-04 16:16
At this point, I am unable to correct this conflict with the Midi QoL module. I have no way of knowing which rolls are legitimate, and which are being thrown away by the module. A fix for this would have to occur inside Midi where it would need to clean up its roll requests to no longer perform unnecessary rolls in the background.

In the meantime, I've marked Midi as a conflicting module in the README and on the package page.

**Closed by flamewave000** 2021-05-04 16:16 UTC
Labels: conflict, investigation
